/**
 * DocMS API
 * Document Management System for small companies Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DocumentLinks from './DocumentLinks';
import TagResponse from './TagResponse';





/**
* The DocumentResponse model module.
* @module model/DocumentResponse
* @version v1
*/
export default class DocumentResponse {
    /**
    * Constructs a new <code>DocumentResponse</code>.
    * @alias module:model/DocumentResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DocumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DocumentResponse} obj Optional instance to populate.
    * @return {module:model/DocumentResponse} The populated <code>DocumentResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentResponse();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('mediaType')) {
                obj['mediaType'] = ApiClient.convertToType(data['mediaType'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagResponse]);
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = DocumentLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} mediaType
    */
    mediaType = undefined;
    /**
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} path
    */
    path = undefined;
    /**
    * @member {Array.<module:model/TagResponse>} tags
    */
    tags = undefined;
    /**
    * @member {module:model/DocumentLinks} _links
    */
    _links = undefined;








}


