/**
 * DocMS API
 * Document Management System for small companies Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Link from './Link';





/**
* The DocumentLinks model module.
* @module model/DocumentLinks
* @version v1
*/
export default class DocumentLinks {
    /**
    * Constructs a new <code>DocumentLinks</code>.
    * @alias module:model/DocumentLinks
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DocumentLinks</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DocumentLinks} obj Optional instance to populate.
    * @return {module:model/DocumentLinks} The populated <code>DocumentLinks</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentLinks();

            
            
            

            if (data.hasOwnProperty('file')) {
                obj['file'] = Link.constructFromObject(data['file']);
            }
            if (data.hasOwnProperty('self')) {
                obj['self'] = Link.constructFromObject(data['self']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Link} file
    */
    file = undefined;
    /**
    * @member {module:model/Link} self
    */
    self = undefined;








}


