/**
 * DocMS API
 * Document Management System for small companies Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Link model module.
* @module model/Link
* @version v1
*/
export default class Link {
    /**
    * Constructs a new <code>Link</code>.
    * @alias module:model/Link
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Link</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Link} obj Optional instance to populate.
    * @return {module:model/Link} The populated <code>Link</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Link();

            
            
            

            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} href
    */
    href = undefined;








}


