/**
 * DocMS API
 * Document Management System for small companies Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TagResponse from './TagResponse';





/**
* The UploadDocumentRequest model module.
* @module model/UploadDocumentRequest
* @version v1
*/
export default class UploadDocumentRequest {
    /**
    * Constructs a new <code>UploadDocumentRequest</code>.
    * @alias module:model/UploadDocumentRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>UploadDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UploadDocumentRequest} obj Optional instance to populate.
    * @return {module:model/UploadDocumentRequest} The populated <code>UploadDocumentRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadDocumentRequest();

            
            
            

            if (data.hasOwnProperty('mediaType')) {
                obj['mediaType'] = ApiClient.convertToType(data['mediaType'], 'String');
            }
            if (data.hasOwnProperty('encoding')) {
                obj['encoding'] = ApiClient.convertToType(data['encoding'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagResponse]);
            }
        }
        return obj;
    }

    /**
    * @member {String} mediaType
    */
    mediaType = undefined;
    /**
    * @member {String} encoding
    */
    encoding = undefined;
    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} path
    */
    path = undefined;
    /**
    * @member {Array.<module:model/TagResponse>} tags
    */
    tags = undefined;








}


