/**
 * DocMS API
 * Document Management System for small companies Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateTagRequest from './model/CreateTagRequest';
import DocumentLinks from './model/DocumentLinks';
import DocumentResponse from './model/DocumentResponse';
import Link from './model/Link';
import SearchResponse from './model/SearchResponse';
import TagLinks from './model/TagLinks';
import TagResponse from './model/TagResponse';
import UploadDocumentRequest from './model/UploadDocumentRequest';
import DocumentsApi from './api/DocumentsApi';
import SearchApi from './api/SearchApi';
import TagsApi from './api/TagsApi';


/**
* Document_Management_System_for_small_companies_Web_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DocMsApi = require('index'); // See note below*.
* var xxxSvc = new DocMsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DocMsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DocMsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DocMsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateTagRequest model constructor.
     * @property {module:model/CreateTagRequest}
     */
    CreateTagRequest,

    /**
     * The DocumentLinks model constructor.
     * @property {module:model/DocumentLinks}
     */
    DocumentLinks,

    /**
     * The DocumentResponse model constructor.
     * @property {module:model/DocumentResponse}
     */
    DocumentResponse,

    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link,

    /**
     * The SearchResponse model constructor.
     * @property {module:model/SearchResponse}
     */
    SearchResponse,

    /**
     * The TagLinks model constructor.
     * @property {module:model/TagLinks}
     */
    TagLinks,

    /**
     * The TagResponse model constructor.
     * @property {module:model/TagResponse}
     */
    TagResponse,

    /**
     * The UploadDocumentRequest model constructor.
     * @property {module:model/UploadDocumentRequest}
     */
    UploadDocumentRequest,

    /**
    * The DocumentsApi service constructor.
    * @property {module:api/DocumentsApi}
    */
    DocumentsApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi
};
